### ISSUE TITLE
Object is not a constructor

### ISSUE THREAD

**Issue by snout-o** [chriscamargo/framer-viewNavigationController#7]
Maybe it's because I'm brand new to Framer and CoffeeScript and I'm doing something obviously wrong - and apologies if so - but I can't seem to get this module to work. I've added the script to the modules folder, added the require statement, and then when I go to instantiate the variable I get the error: `TypeError: Object is not a constructor (evaluating 'new ViewNavigationController')`. Any suggestions where I might be going wrong here? 

`ViewNavigationController = require "ViewNavigationController";`
`vnc = new ViewNavigationController;`

(I also tried wrapping the require statement in braces but that made no difference.)

**Comment by chriscamargo** [comment]
Hey @sibbaldl, thanks for reporting this. I don't think I've seen this myself. Do you happen to have a prototype that I can troubleshoot?

**Comment by snout-o** [comment]
Sure no problem but I honestly don't know what you'll get from this as it's a wholly new project with only your component added to the modules folder. I've included a screenshot in the zip so you can see what I see. good luck!
[tester.framer.zip](https://github.com/chriscamargo/framer-viewNavigationController/files/518653/tester.framer.zip)

**Comment by snout-o** [comment]
Just to add to this, if I use the brace notation when including your class i.e.

`{ViewNavigationController} = require "ViewNavigationController";`

I do actually get a different error message that might help you (scpeengrab attached):

`TypeError: undefined is not an object (evaluating 'this[DefinedPropertiesValuesKey][k]=v')`
![othererror](https://cloud.githubusercontent.com/assets/505678/19259322/c26ecf6e-8fc3-11e6-8d29-13b2386dd174.jpg)

**Comment by chriscamargo** [comment]
Hey @sibbaldl, I just published an update to the module that should fix this error in the latest version of Framer. Give it a shot and let me know if it works for you.

**Comment by snout-o** [comment]
I've tried the ViewNavigationController.coffee file version dated 7th October @ 14:39 in a new project, but unless there's something else I need to do there appears to be no change. I still get the first error I reported and the second error when using brace notation. Sorry :(

**Comment by jordandobson** [comment]
Chris you may want to update the single module file as well.

**Comment by chriscamargo** [comment]
@sibbaldl I think the only thing missing was my brain. @jordandobson caught my mistake. I was only updating the example, and not the module. I've just updated it. Give it another try with the latest version of Framer and a blank file.

**Comment by chriscamargo** [comment]
@sibbaldl –  it sounds like you were using the right version... Your zip file didn't link properly. Can you post the prototype by clicking "Share" in the Framer Studio toolbar? Just post the URL here.

**Comment by chriscamargo** [comment]
And to be clear, the only two lines you need to start are:

``` coffeescript
{ViewNavigationController} = require "ViewNavigationController"

vnc = new ViewNavigationController
```

**Comment by snout-o** [comment]
Okay great, the most recent version appears to work now 👍 
It doesn't automatically show a back button like the instructions suggest (i.e. I can't _see_ a back button) but there is _something_ there because I can click the top left corner and it'll do the back action.
Anyway thanks for nailing the issue and thanks for a very handy module :)
[Link](http://share.framerjs.com/hb3cotin9ikb/)

**Comment by chriscamargo** [comment]
No problem. Glad we got you sorted. :)

One feature that I haven't documented is debug mode. If you want to be able to visualize the back button, you can turn it on by setting `debugMode: true`.

``` coffeescript
vnc = new ViewNavigationController
    debugMode: true
```
